### ISSUE TITLE
The serve command requires to be run in an Angular project, but a project definition could not be found.

### ISSUE THREAD

**Issue by kamleshwebtech** [cornflourblue/angular-7-role-based-authorization-example#2]
I have cloned the repository on my mac then installed npm to download required modules then run 'ng serve' command to run the application, it returns me an error like 

'The serve command requires to be run in an Angular project, but a project definition could not be found.'

Kindly help me how can i solve this issue and run your solution on my mac. Thank you so much in advance.

Ps. See attached screenshot.
![screenshot 2019-01-09 at 4 40 00 pm](https://user-images.githubusercontent.com/43021973/50896098-05363300-142e-11e9-86e4-dfc9b4a486d6.png)

**Comment by sprakash1** [comment]
same error for me

**Comment by cornflourblue** [comment]
This project doesn't use the angular cli, it uses webpack directly. To start run the command `npm start`

**Comment by aayush-18** [comment]
i have exactly the same issue. I cloned a repository of Barcode Scanner by Quagga. i did the ng install to download the necessary components but afterwards when i try to run ng build it is not working.

**Comment by MU8T4Z4** [comment]
run command ( npm install) to update node models.

**Comment by abhisheikreddy646** [comment]
while am getting this error "The serve command requires to be run in an Angular project, but a project definition could not be found" i tried npm install, and updated "ng update @angular/cli --migrate-only --from=1.7.3" still am getting this error .what is the solutions?

**Comment by vrdevendra** [comment]
Make sure you are in correct repository or opening correct folder. 
As shown in below attachment, you need to open that folder in angular. 
![Capture](https://user-images.githubusercontent.com/52192530/70377227-e2f7ae80-1937-11ea-87a4-0cd0dc4549b7.PNG)

**Comment by HomeroLara** [comment]
@svdevendra yep, this worked. thanks!

**Comment by khaldounjalem** [comment]
@svdevendra
Please, what exactly did you do?

**Comment by vrdevendra** [comment]
@khaldounjalem 
Nothing special, look closely error saying itself "The serve command requires to be run in an Angular project, but a project definition could not be found" it means that the command which you are trying to execute is run on angular project only so either you opened wrong project (other than angular) or wrong directory.

**Comment by ranjitben10** [comment]
all solutions available here is not working for me

**Comment by ranjitben10** [comment]
https://github.com/abhianshu2020/Hearti-Health
download files from here and run it..

**Comment by Ayesha-Mulla** [comment]
Please check if node modules are installed properly. If yes, refresh node module folder and try running app in parent directory.

**Comment by angulodev** [comment]
> @khaldounjalem
> Nada especial, mira de cerca el error diciéndose a sí mismo "El comando de servicio requiere ejecutarse en un proyecto angular, pero no se pudo encontrar una definición de proyecto", significa que el comando que está intentando ejecutar se ejecuta solo en un proyecto angular abriste un proyecto incorrecto (que no sea angular) o un directorio incorrecto.

excelente respuesta, muchas gracias

**Comment by angulodev** [comment]
para solucionar 

cd (name app)
luego ejecuta 
ng serve
** ng serve -o  // asi levantas el navegador por defecto

**Comment by Clinzho1996** [comment]
pls im having the same issue too
its saying "The serve command requires to be run in an Angular project, but a project definition could not be found.

**Comment by Clinzho1996** [comment]
but its sorted now. i opened the project folder then run the git bash, then "ng serve" and it worked perfectly.

**Comment by lorran-mariuba** [comment]
> but its sorted now. i opened the project folder then run the git bash, then "ng serve" and it worked perfectly.

I did the same thing, but it's not working. I don't know what I have to do. I'm in the correct repository and the right project. Someone can help?

**Comment by abvarunjain** [comment]
> This project doesn't use the angular cli, it uses webpack directly. To start run the command `npm start`

it works

**Comment by ganeshsthube** [comment]
Igot the error "The serve command requires to be run in an Angular project, but a project definition could not be found" in two different condition 
1)when our project is just static and we are running this project in from different folder.
solution :- Go to the same folder in terminal using "cd" command where our project is located.

2)When we clone dynamic project from github and then try to run "ng serve" command in terminal. At that time you will get same error
Solution  :-Run the ".sln" file using visual studio.

**Comment by Dinuda** [comment]
None of them work for me.

**Comment by paulmunyao** [comment]
> This project doesn't use the angular cli, it uses webpack directly. To start run the command `npm start`

Hi I have run the same command but I'm getting an error sating electron not found
Kindly advise
